
CC=g++
CXXFLAGS= -std=c++11 -g -Wall -I./ 
LDFLAGS= -lpthread 

LIB_SOURCES= \
		core/core_workload.cc  \
		db/db_factory.cc   \
		db/hashtable_db.cc  \

##METADB
METADB_SOURCES= db/metadb_db.cc
METADB_LIBRARY= -lmetadb -lpmem
METADB_DEFS= -DYCSB_METADB
METADB_OBJECTS=$(METADB_SOURCES:.cc=.o)
##

##leveldb
LEVELDB_SOURCES= db/leveldb_db.cc
LEVELDB_LIBRARY= -lleveldb -lsnappy
LEVELDB_DEFS= -DYCSB_LEVELDB
LEVELDB_OBJECTS=$(LEVELDB_SOURCES:.cc=.o)
##

##rocksdb
ROCKSDB_SOURCES= db/rocksdb_db.cc
ROCKSDB_LIBRARY= -lrocksdb -lsnappy
ROCKSDB_DEFS= -DYCSB_ROCKSDB
ROCKSDB_OBJECTS=$(ROCKSDB_SOURCES:.cc=.o)
##

##hbkv
HBKV_SOURCES= db/hbkv_db.cc
HBKV_LIBRARY= -lnvmbtree -lpmem -lpmemobj
HBKV_DEFS= -DYCSB_HBKV
HBKV_OBJECTS=$(ROCKSDB_SOURCES:.cc=.o)
##

OBJECTS=$(LIB_SOURCES:.cc=.o)
EXEC=ycsbc

ONLY_METADB_SOURCES=$(LIB_SOURCES) $(METADB_SOURCES)
ONLY_LEVELDB_SOURCES=$(LIB_SOURCES) $(LEVELDB_SOURCES)
ONLY_ROCKSDB_SOURCES=$(LIB_SOURCES) $(ROCKSDB_SOURCES)
ONLY_HBKV_SOURCES=$(LIB_SOURCES) $(HBKV_SOURCES)
ALL_SOURCES=$(LIB_SOURCES) $(METADB_SOURCES) $(LEVELDB_SOURCES) $(ROCKSDB_SOURCES) $(ONLY_HBKV_SOURCES)

all: clean
	$(CC) $(CXXFLAGS) $(METADB_DEFS) $(LEVELDB_DEFS) ycsbc.cc $(ALL_SOURCES) -o $(EXEC) $(LDFLAGS) $(METADB_LIBRARY) $(LEVELDB_LIBRARY)

metadb: clean
	$(CC) $(CXXFLAGS) $(METADB_DEFS) ycsbc.cc $(ONLY_METADB_SOURCES) -o $(EXEC) $(LDFLAGS) $(METADB_LIBRARY)

leveldb: clean
	$(CC) $(CXXFLAGS) $(LEVELDB_DEFS) ycsbc.cc $(ONLY_LEVELDB_SOURCES) -o $(EXEC) $(LDFLAGS) $(LEVELDB_LIBRARY)

rocksdb: clean
	$(CC) $(CXXFLAGS) $(ROCKSDB_DEFS) ycsbc.cc $(ONLY_ROCKSDB_SOURCES) -o $(EXEC) $(LDFLAGS) $(ROCKSDB_LIBRARY)

hbkv: clean
	$(CC) $(CXXFLAGS) $(HBKV_DEFS) ycsbc.cc $(ONLY_HBKV_SOURCES) -o $(EXEC) $(LDFLAGS) $(HBKV_LIBRARY)

clean:
	rm -f $(EXEC) 

.PHONY: clean leveldb metadb

